name: Update TOC Interface versions

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update TOC Interface versions
        uses: p3lim/toc-interface-updater@v4
        with:
          flavor: |
            retail
            classic_era
            classic
            tbc
            wrath
            mists
            anniversary

      - name: Create pull request
        uses: peter-evans/create-pull-request@v8
        with:
          title: Update Interface versions
          commit-message: Update Interface versions
          branch: update/interface
          delete-branch: true
